/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ureka.framework.java;

class AppTest {
    // TODO:
    // 1. Uncomment the following files after unit testing:
    // FlowApplyUTicket, Executor, MsgSender, MsgReceiver
    // 2. resource.communication is not tested yet
    // since BluetoothService is not needed in simulation stage.
}